count=input().split()
A,B,C=list(map(int,count))
# print((int(A)+int(B))%int(C))
# print(((int(A)%int(C)) + (int(B)%int(C)))%int(C))
# print((int(A)*int(B))%int(C))
# print(((int(A)%int(C)) * (int(B)%int(C)))%int(C))
print((A+B)%C)
print(((A%C) + (B%C))%C)
print( (A*B)%C)
print(((A%C) * (B%C))%C)